# Generated by Django 3.2.4 on 2024-09-18 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("game_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(blank=True, max_length=3000, null=True)),
                ("weight", models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ("price", models.PositiveIntegerField()),
                ("fandom_link", models.CharField(blank=True, max_length=2000, null=True)),
                ("is_craftable", models.BooleanField(blank=True, default=False)),
                ("is_dismantlable", models.BooleanField(blank=True, default=False)),
                ("is_usable", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="RecipeComponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Tier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color_hex", models.CharField(default="FFFFFF", max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BaseAlchemyItem",
            fields=[
                (
                    "baseitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.baseitem",
                    ),
                ),
                ("charges", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("item.baseitem",),
        ),
        migrations.CreateModel(
            name="CraftingComponent",
            fields=[
                (
                    "baseitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.baseitem",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        default="assets/item/default_craft_component.png",
                        null=True,
                        upload_to="uploads/item/general/craft_components/",
                    ),
                ),
                (
                    "craft_type",
                    models.CharField(
                        choices=[("alchemy", "Alchemy"), ("crafting", "Crafting"), ("both", "Both")], max_length=50
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("item.baseitem",),
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(max_length=400)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sources", to="item.baseitem"
                    ),
                ),
            ],
        ),
    ]
