# Generated by Django 3.2.4 on 2024-01-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alchemy', '0005_alter_decotion_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomb',
            name='img',
            field=models.ImageField(default='assets/default_bomb.png', null=True, upload_to='alchemy/bombs/'),
        ),
        migrations.AlterField(
            model_name='decotion',
            name='img',
            field=models.ImageField(default='assets/default_decotion.png', null=True, upload_to='alchemy/decotions/'),
        ),
        migrations.AlterField(
            model_name='oil',
            name='img',
            field=models.ImageField(default='assets/default_oil.png', null=True, upload_to='alchemy/oils/'),
        ),
        migrations.AlterField(
            model_name='potion',
            name='img',
            field=models.ImageField(default='assets/default_potion.png', null=True, upload_to='alchemy/potions/'),
        ),
    ]
