# Generated by Django 3.2.4 on 2024-01-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alchemy', '0009_auto_20240110_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomb',
            name='game_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='decotion',
            name='game_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='oil',
            name='game_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='potion',
            name='game_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
