# Generated by Django 3.2.4 on 2024-01-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alchemy', '0011_remove_bomb_duration_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomb',
            name='duration_sec',
            field=models.PositiveIntegerField(default=1800),
        ),
    ]
