# Generated by Django 3.2.4 on 2024-01-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tier",
            name="color_hex",
            field=models.CharField(default="FFFFFF", max_length=6),
        ),
    ]
