# Generated by Django 3.2.4 on 2024-01-23 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('core', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipecomponent',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.baseitem'),
        ),
        migrations.AddField(
            model_name='recipecomponent',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='items.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craft_recipes', to='items.baseitem'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_craft_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_items.baseitem_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tier'),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.type'),
        ),
        migrations.AddField(
            model_name='baseitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
