# Generated by Django 3.2.4 on 2024-02-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_baseitem_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source',
            field=models.CharField(max_length=400),
        ),
    ]
