# Generated by Django 3.2.4 on 2024-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_source_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='potion',
            name='potion_type',
            field=models.CharField(choices=[('potion', 'Potion'), ('decotion', 'Decotion')], default='potion', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='potion',
            name='charges',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='potion',
            name='duration_sec',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='potion',
            name='tox_points',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='Decotion',
        ),
    ]
